[project]
name = "some-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiogram>=3.20.0.post0",
    "environs>=14.2.0",
    "pillow>=11.2.1",
    "setuptools>=80.9.0",
    "wheel>=0.45.1",
]
